create database CID;

create table DepartamentoPolicia(
    codDP int4 generated by default as identity constraint DP_pk primary key,
    distritoDP int4 not null
);
comment on table departamentopolicia is 'Tabela dos departamentos de policia';
comment on column departamentopolicia.coddp is 'codigo do departamento de policia';
comment on column departamentopolicia.distritodp  is 'distrito do departamento de policia';

create table Estado(
    codEstado int4 generated by default as identity constraint Estado_pk primary key,
    codibgeEstado int4 not null,
    nomEstado varchar(50)
);

comment on table Estado is 'tabela de estados';
comment on column Estado.codEstado is 'codigo do estado';
comment on column Estado.codIbgeEstado is 'codigo IBGE do estado';
comment on column estado.nomestado  is 'nome do Estado';

create table Cidade(
    codCidade int4 generated by default as identity constraint Cidade_pk primary key,
    ufcidade varchar(3) not null,
    codibgeCidade int4 not null,
    nomeCidade varchar(50) not null,
    codEstado int4 constraint cidade_codEstado_fk references Estado(codEstado)
);

comment on table cidade is 'tabela de cidades';
comment on column Cidade.codCidade IS 'Codigo da cidade';
comment on column Cidade.ufCidade IS 'UF da cidade';
comment on column Cidade.codIbgeCidade IS 'Codigo do IBGE da Cidade';
comment on column Cidade.nomeCidade IS 'Nome da cidade';

create table tipo_Ocorrencia(
    codtipocorrencia int4 generated by default as identity constraint tipo_Ocorrencia_pk primary key,
    descOcorencia varchar(255) not null
);

comment on table tipo_ocorrencia is 'tabela dos tipos de ocorrencia';
COMMENT ON COLUMN tipo_Ocorrencia.codtipocorrencia IS 'Codigo do tipo de ocorrencia';
COMMENT ON COLUMN tipo_Ocorrencia.descocorencia IS 'Descricao do acontecimento';

create table Funcionario(
    codFun int4 generated by default as identity constraint Fun_pk primary key,
    cargoFun int4 not null,
    codDP int4 constraint fun_codDP_fk references DepartamentoPolicia(codDP),
    dpatuacaoFun int4 not null,
    codPessoa int4
);

comment on table funcionario is 'tabela de funcionarios';
COMMENT ON COLUMN Funcionario.codfun IS 'codigo do funcionario';
COMMENT ON COLUMN Funcionario.cargoFun IS 'Cargo do funcionario';
COMMENT ON COLUMN Funcionario.dpatuacaofun IS 'DP que o funcionario esta atuando';

create table Pessoa(
    codPessoa int4 generated by default as identity constraint Pessoa_pk primary key,
    nomPessoa varchar(40) not null,
    estcivilPessoa varchar(40) not null,
    datanascPessoa date not null,
    cpfPessoa numeric(11,0) unique,
    numtelePessoa numeric (14,0) not null,
    emailPessoa varchar(40) not null,
    codFun int4
);

COMMENT ON TABLE Pessoa IS ' Tabela de pessoas para registrar o BO';
COMMENT ON COLUMN Pessoa.codPessoa IS 'Codigo Pessoa';
COMMENT ON COLUMN Pessoa.nomPessoa IS 'Nome da Pessoa';
COMMENT ON COLUMN Pessoa.cpfPessoa IS 'CPF da pessoa';
COMMENT ON COLUMN Pessoa.estCivilPessoa IS 'Estado civil da Pessoa';
COMMENT ON COLUMN Pessoa.dataNascPessoa IS 'Data de nascimento da pessoa';
COMMENT ON COLUMN Pessoa.numTelePessoa IS 'numero de telefone da pessoa';
COMMENT ON COLUMN Pessoa.emailPessoa IS 'E-mail da pessoa';

create table BO(
    codBO int4 generated by default as identity constraint BO_pk primary key,
    dataBO date not null,
    localBO varchar(50) not null,
    sitBO bool not null,
    codFun int4 constraint BO_codFun_fk references Funcionario(codFun)
);

comment on table BO is 'tabela de boletins de ocorrencia';
COMMENT ON COLUMN BO.codBO IS 'codigo do boletim de ocorrencia';
COMMENT ON COLUMN BO.dataBO IS 'Data que foi gerado o boletim de ocorrencia';
COMMENT ON COLUMN BO.localBO IS 'Local que foi feito o BO';
COMMENT ON COLUMN BO.sitBO IS 'Situacao do Boletim de Ocorrencia';

create table Ocorrencia(
    codOcorrencia int4 generated by default as identity constraint Ocorrencia_pk primary key,
    dataOcorrencia date not null,
    localOcorrencia varchar(255) not null,
    numenvolvidos int4 not null,
    codtipocorrencia int4 constraint ocorrencia_codtipocorrencia_fk references tipo_ocorrencia(codtipocorrencia),
    codBO int4 constraint ocorrencia_codBO_fk references BO(codBO)
);

comment on table ocorrencia  is 'tabela de ocorrencias';
COMMENT ON COLUMN Ocorrencia.dataOcorrencia IS 'Data que aconteceu o fato';
COMMENT ON COLUMN Ocorrencia.localOcorrencia IS 'Local do Fato';
COMMENT ON COLUMN Ocorrencia.numEnvolvidos IS 'quantidade  de envolvidos no fato';

CREATE TABLE Endereco (
    cepEndereco SERIAL NOT NULL, 
    ruaEndereco varchar(50) NOT NULL, 
    bairroEndereco varchar(50) NOT NULL, 
    compEndereco varchar(50) NOT NULL, 
    numEndereco int4 NOT NULL, 
    codPessoa int4 NOT NULL, 
    codCidade int4 NOT NULL, 
    codigoDP int4 NOT NULL, 
    PRIMARY KEY (cepEndereco)
);

comment on table endereco is 'tabela de endereços';
COMMENT ON COLUMN Endereco.ruaEndereco IS 'Rua do Endereco';
COMMENT ON COLUMN Endereco.bairroEndereco IS 'Bairro do endereco';
COMMENT ON COLUMN Endereco.compEndereco IS 'Complemento do endereco';
COMMENT ON COLUMN Endereco.numEndereco IS 'Numero do Endereco';
COMMENT ON COLUMN Endereco.cepEndereco IS 'Cep do Endereco';

alter table Funcionario add constraint fun_codPessoa_fk foreign key (codPessoa) references Pessoa(codPessoa);
alter table Pessoa add constraint Pessoa_codFun_fk foreign key (codFun) references Funcionario(codFun);