create database CID;

create table DepartamentoPolicia(
    codDP int4 generated by default as identity constraint DP_pk primary key,
    distritoDP int4 not null
);

create table Estado(
    codEstado int4 generated by default as identity constraint Estado_pk primary key,
    codibgeEstado int4 not null,
    nomEstado varchar(50)
);

create table Cidade(
    codCidade int4 generated by default as identity constraint Cidade_pk primary key,
    ufcidade varchar(3) not null,
    codibgeCidade int4 not null,
    nomeCidade varchar(50) not null,
    codEstado int4 constraint cidade_codEstado_fk references Estado(codEstado)
);

create table tipo_Ocorrencia(
    codtipocorrencia int4 generated by default as identity constraint tipo_Ocorrencia_pk primary key,
    descOcorencia varchar(255) not null
);

create table Funcionario(
    codFun int4 generated by default as identity constraint Fun_pk primary key,
    cargoFun int4 not null,
    codDP int4 constraint fun_codDP_fk references DepartamentoPolicia(codDP),
    codPessoa int4
);

create table Pessoa(
    codPessoa int4 generated by default as identity constraint Pessoa_pk primary key,
    nomPessoa varchar(40) not null,
    estcivilPessoa varchar(40) not null,
    datanascPessoa date not null,
    cpfPessoa numeric(11,0) unique,
    numtelePessoa numeric (14,0) not null,
    emailPessoa varchar(40) not null,
    codFun int4
);

create table BO(
    codBO int4 generated by default as identity constraint BO_pk primary key,
    dataBO date not null,
    localBO varchar(50) not null,
    sitBO bool not null,
    codFun int4 constraint BO_codFun_fk references Funcionario(codFun)
);

create table Ocorrencia(
    codOcorrencia int4 generated by default as identity constraint Ocorrencia_pk primary key,
    dataOcorrencia date not null,
    localOcorrencia varchar(255) not null,
    numenvolvidos int4 not null,
    codtipocorrencia int4 constraint ocorrencia_codtipocorrencia_fk references tipo_ocorrencia(codtipocorrencia),
    codBO int4 constraint ocorrencia_codBO_fk references BO(codBO)
);

CREATE TABLE Endereco (
    cepEndereco SERIAL NOT NULL, 
    ruaEndereco varchar(50) NOT NULL, 
    bairroEndereco varchar(50) NOT NULL, 
    compEndereco varchar(50) NOT NULL, 
    numEndereco int4 NOT NULL, 
    codPessoa int4 NOT NULL, 
    codCidade int4 NOT NULL, 
    codigoDP int4 NOT NULL, 
    PRIMARY KEY (cepEndereco)
);

COMMENT ON COLUMN Endereco.cepEndereco IS 'Cep do Endereco';

alter table Funcionario add constraint fun_codPessoa_fk foreign key (codPessoa) references Pessoa(codPessoa);
alter table Pessoa add constraint Pessoa_codFun_fk foreign key (codFun) references Funcionario(codFun);
