create database CID;

create table departamento_policia(
    cod_dp int4 generated by default as identity constraint dp_pk primary key,
    distrito_dp int4 not null
);
comment on table departamento_policia is 'Tabela dos departamentos de policia';
comment on column departamento_policia.cod_dp is 'codigo do departamento de policia';
comment on column departamento_policia.distrito_dp  is 'distrito do departamento de policia';

create table estado(
    cod_estado int4 generated by default as identity constraint estado_pk primary key,
    cod_ibge_estado int4 not null,
    nome_estado varchar(50)
);
comment on table estado is 'tabela de estados';
comment on column estado.cod_estado is 'codigo do estado';
comment on column estado.cod_ibge_estado is 'codigo IBGE do estado';
comment on column estado.nome_estado is 'nome do Estado';

create table cidade(
    cod_cidade int4 generated by default as identity constraint cidade_pk primary key,
    uf_cidade varchar(3) not null,
    cod_ibge_cidade int4 not null,
    nome_cidade varchar(50) not null,
    cod_estado int4 constraint cidade_cod_estado_fk references estado(cod_estado)
);
comment on table cidade is 'tabela de cidades';
comment on column cidade.cod_cidade is 'Codigo da cidade';
comment on column cidade.uf_cidade is 'UF da cidade';
comment on column cidade.cod_ibge_cidade is 'Codigo do IBGE da Cidade';
comment on column cidade.nome_cidade is 'Nome da cidade';

create table tipo_ocorrencia(
    cod_tipo_ocorrencia int4 generated by default as identity constraint tipo_ocorrencia_pk primary key,
    desc_ocorrencia varchar(255) not null
);
comment on table tipo_ocorrencia is 'tabela dos tipos de ocorrencia';
comment on column tipo_ocorrencia.cod_tipo_ocorrencia is 'Codigo do tipo de ocorrencia';
comment on column tipo_ocorrencia.desc_ocorrencia is 'Descricao do acontecimento';

create table funcionario(
    cod_fun int4 generated by default as identity constraint fun_pk primary key,
    cargo_fun int4 not null,
    cod_dp int4 constraint fun_cod_dp_fk references departamento_policia(cod_dp),
    dp_atuacao_fun int4 not null,
    cod_pessoa int4
);
comment on table funcionario is 'tabela de funcionarios';
comment on column funcionario.cod_fun is 'codigo do funcionario';
comment on column funcionario.cargo_fun is 'Cargo do funcionario';
comment on column funcionario.dp_atuacao_fun is 'DP que o funcionario esta atuando';

create table pessoa(
    cod_pessoa int4 generated by default as identity constraint pessoa_pk primary key,
    nome_pessoa varchar(40) not null,
    est_civil_pessoa varchar(40) not null,
    data_nasc_pessoa date not null,
    cpf_pessoa numeric(11,0) unique,
    num_tele_pessoa numeric(14,0) not null,
    email_pessoa varchar(40) not null,
    cod_fun int4
);
comment on table pessoa is 'Tabela de pessoas para registrar o BO';
comment on column pessoa.cod_pessoa is 'Codigo Pessoa';
comment on column pessoa.nome_pessoa is 'Nome da Pessoa';
comment on column pessoa.cpf_pessoa is 'CPF da pessoa';
comment on column pessoa.est_civil_pessoa is 'Estado civil da Pessoa';
comment on column pessoa.data_nasc_pessoa is 'Data de nascimento da pessoa';
comment on column pessoa.num_tele_pessoa is 'Numero de telefone da pessoa';
comment on column pessoa.email_pessoa is 'E-mail da pessoa';

create table bo(
    cod_bo int4 generated by default as identity constraint bo_pk primary key,
    data_bo date not null,
    local_bo varchar(50) not null,
    sit_bo bool not null,
    cod_fun int4 constraint bo_cod_fun_fk references funcionario(cod_fun)
);
comment on table bo is 'tabela de boletins de ocorrencia';
comment on column bo.cod_bo is 'codigo do boletim de ocorrencia';
comment on column bo.data_bo is 'Data que foi gerado o boletim de ocorrencia';
comment on column bo.local_bo is 'Local que foi feito o BO';
comment on column bo.sit_bo is 'Situacao do Boletim de Ocorrencia';

create table ocorrencia(
    cod_ocorrencia int4 generated by default as identity constraint ocorrencia_pk primary key,
    data_ocorrencia date not null,
    local_ocorrencia varchar(255) not null,
    num_envolvidos int4 not null,
    cod_tipo_ocorrencia int4 constraint ocorrencia_cod_tipo_ocorrencia_fk references tipo_ocorrencia(cod_tipo_ocorrencia),
    cod_bo int4 constraint ocorrencia_cod_bo_fk references bo(cod_bo)
);
comment on table ocorrencia is 'tabela de ocorrencias';
comment on column ocorrencia.cod_ocorrencia is 'codigo da ocorrencia';
comment on column ocorrencia.data_ocorrencia is 'Data que aconteceu o fato';
comment on column ocorrencia.local_ocorrencia is 'Local do Fato';
comment on column ocorrencia.num_envolvidos is 'quantidade de envolvidos no fato';

create table endereco (
    cep_endereco SERIAL NOT NULL, 
    rua_endereco varchar(50) NOT NULL, 
    bairro_endereco varchar(50) NOT NULL, 
    comp_endereco varchar(50) NOT NULL, 
    num_endereco int4 NOT NULL, 
    cod_pessoa int4 NOT NULL, 
    cod_cidade int4 NOT NULL, 
    codigo_dp int4 NOT NULL, 
    PRIMARY KEY (cep_endereco)
);
comment on table endereco is 'tabela de endereços';
comment on column endereco.cep_endereco is 'Cep do Endereco';
comment on column endereco.rua_endereco is 'Rua do Endereco';
comment on column endereco.bairro_endereco is 'Bairro do endereco';
comment on column endereco.comp_endereco is 'Complemento do endereco';
comment on column endereco.num_endereco is 'Numero do Endereco';

alter table funcionario add constraint fun_cod_pessoa_fk foreign key (cod_pessoa) references pessoa(cod_pessoa);
alter table pessoa add constraint pessoa_cod_fun_fk foreign key (cod_fun) references funcionario(cod_fun);
