DROP TABLE IF EXISTS ocorrencia CASCADE;

DROP TABLE IF EXISTS bo CASCADE;

DROP TABLE IF EXISTS funcionario CASCADE;

DROP TABLE IF EXISTS pessoa CASCADE;

DROP TABLE IF EXISTS tipo_ocorrencia CASCADE;

DROP TABLE IF EXISTS departamento_policia CASCADE;

DROP TABLE IF EXISTS bairro CASCADE;

DROP TABLE IF EXISTS cidade CASCADE;

DROP TABLE IF EXISTS estado CASCADE;